### ISSUE TITLE
How do I make Status Bar work?

### ISSUE THREAD

**Issue by ianTevesAcc** [powerline/fonts#399]
I'm so sorry. I've tried so hard but I really can't make the Status Bar work for some unknown / my stupid ass brain can't find out the reason. I have a Powerline font installed as well as updated it in the code. But it's still not working. 
Can I get some help?

Image of what the Status Bar looks like. Its the green dot and white arrow at the bottom.
![image](https://github.com/powerline/fonts/assets/105651670/53b9dfe4-73bd-49e6-99a3-1e7dc4471c26)
![image](https://github.com/powerline/fonts/assets/105651670/a28a23fd-a021-410d-98b5-a7f2120faafa)

Here is my css code for the status bar.
```css
div.status-bar-item.plugin-obsidian-vimrc-support {
    /* Papercolor theme */
    --text-color-normal: #585858;
    --text-color-insert: #005f87;
    --text-color-visual: white;
    --text-color-replace: white;
  
    --background-color-normal: #eeeeee;
    --background-color-insert: #eeeeee;
    --background-color-visual: #d75f00;
    --background-color-replace: #d70087;
  }
  
  div.status-bar-item.plugin-obsidian-vimrc-support {
    /* 
      Move to bottom left corner and discard top/left/bottom space
      from container paddings.
     */
    order: -9999;
    margin: 0;
  
    /* 
      We have the :after pseudo-element next, so padding-right
      is not needed
      */
    padding-right: 0px;
    padding-left: 1em;
  
    /* Use Monospace font */
    font-family: 'Ubuntu Mono derivative Powerline'; /* !!! Needs to be a powerline font */
    font-weight: bold;
    font-size: 1.2em;
  
    /* Clear spaces made from radius borders */
    border-top-right-radius: 0px;
    border-bottom-right-radius: 0px;
  }
  
  div.status-bar-item.plugin-obsidian-vimrc-support:after {
    /* Powerline separator character */
    content: '';
    position: relative;
    font-size: 1.5rem;
    left: 0.9rem;
  
    /* Fine adjust the position */
    margin-top: 0.1rem;
  }
  
  /* Normal */
  div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="normal"]:after {
    color: var(--background-color-normal);
  }
  div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="normal"] {
    color: var(--text-color-normal);
    background-color: var(--background-color-normal);
  }
  
  /* Insert */
  div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="insert"]:after {
    color: var(--background-color-insert);
  }
  div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="insert"] {
    color: var(--text-color-insert);
    background-color: var(--background-color-insert);
  }
  
  /* Visual */
  div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="visual"]:after {
    color: var(--background-color-visual);
  }
  div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="visual"] {
    color: var(--text-color-visual);
    background-color: var(--background-color-visual);
  }
  
  /* Replace */
  div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="replace"]:after {
    color: var(--background-color-replace);
  }
  div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="replace"] {
    color: var(--text-color-replace);
    background-color: var(--background-color-replace);
  }
  ```
  
  What am I doing wrong?
